---
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
  client:
    #register-with-eureka: false
    service-url:
       defaultZone: http://user:123456@localhost:8762/eureka/
spring:
  application:
    name: SpringCloudEurekaServer01
  profiles: peer1
  security:
    user:
      name: user
      password: 123456


---

server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    #register-with-eureka: false
    service-url:
       defaultZone: http://user:123456@localhost:8761/eureka/  #配置账号密码
spring:
  application:
    name: SpringCloudEurekaServer02
  profiles: peer2
  security: #开启密码登陆
    user:
      name: user
      password: 123456
