eureka:
  client:
    service-url:
      defaultZone: http://spring-cloud-eureka-server01:8761/eureka/,http://spring-cloud-eureka-server02:8761/eureka/
  instance:
    prefer-ip-address: true  #ip注册
spring:
  application:
    name: SpringCloudEurekaClient01
server:
  port: 8846
feign:
  hystrix:
    enabled: true
  client:
    config:
      #ribbon的超时时间
      remote-service:           #服务名，填写default为所有服务
        connectTimeout: 3_000
        readTimeout: 3_000
