eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true  #ip注册
spring:
  application:
    name: SpringCloudEurekaClient01
server:
  port: 8846
#ribbon的超时时间
feign:
  client:
    config:
      remote-service:           #服务名，填写default为所有服务
        connectTimeout: 3_000
        readTimeout: 3_000