eureka:
  client:
    service-url:
      defaultZone: http://user:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true  #ip注册
spring:
  application:
    name: SpringCloudEurekaClient01
server:
  port: 8846
