
server:
  port: 8762
eureka:
  client:
    #register-with-eureka: false
    service-url:
       defaultZone: http://spring-cloud-eureka-server01:8761/eureka/  #配置账号密码
  instance:
    prefer-ip-address: true
spring:
  application:
    name: spring-cloud-eureka-server
#  security: #开启密码登陆
#    user:
#      name: user
#      password: 123456
